language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"

matrix:
  allow_failures:
    - perl: "5.20"

notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: always
    on_failure: always
  irc: "irc.perl.org#metacpan-travis"

env:
  - ES_VERSION=2.3.1

before_install:
  - cpanm -n Devel::Cover::Report::Coveralls
  - cpanm -n Carton
  - "mkdir /tmp/elasticsearch"
  - "wget -O - https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/elasticsearch -d -D es.path.data=/tmp -D es.index.store.type=memory -D es.discovery.zen.ping.multicast.enabled=false -D es.http.port=9900 -D es.cluster.name=testing"

install:
  - 'carton install'

script:
  # Devel::Cover isn't in the cpanfile
  # but if it's installed into the global dirs this should work.
  - ES=localhost:9200 HARNESS_PERL_SWITCHES=-MDevel::Cover=+ignore,local carton exec prove -lvr t

after_success:
  - cover -report coveralls
